services:
  middleware:
    build: .
    image: chamataiga:latest
    container_name: chamataiga
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./certs:/app/certs:ro
      - ./config/application.yaml:/app/config/application.yaml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
