server:
  port: 8081

taiga:
  api:
    url: ${TAIGA_URL:http://localhost:9000/api/v1}
    username: ${TAIGA_USERNAME:taiga}
    password: ${TAIGA_PASSWORD:taiga}
  web:
    url: ${TAIGA_WEB_URL:http://localhost:9000}
  routing:
    fallback-project-name: Diversos
    entity-mappings:
      - glpi-entity-name: Projeto 1
        taiga-project-name: Primeiro Serviço
      - glpi-entity-name: Diversos
        taiga-project-name: Diversos

glpi:
  api:
    url: ${GLPI_URL:http://localhost:8080/apirest.php}
    app-token: ${GLPI_APP_TOKEN:app_token}
    user-token: ${GLPI_USER_TOKEN:user_token}
    category-that-send-to-taiga: Desenvolvimento
    assignee-that-send-to-taiga: tech
  plugin-fields:
    private-ticket-status-block-name: Informações do Taiga
    public-ticket-status-block-name: Progresso do chamado
    private-fields:
      id-taiga: ID Taiga
      link-taiga: Link Taiga
    public-fields:
      status-chamado: Status do chamado
      data-prevista: Conclusão prevista
    status-inicial: Novo
  status-map:
    - taiga: New
      glpi: Novo
    - taiga: In progress
      glpi: Em andamento
    - taiga: Ready for test
      glpi: Pronto para teste
    - taiga: Done
      glpi: Concluído
    - taiga: Archived
      glpi: Arquivado
    - taiga: Closed
      glpi: Fechado
    - taiga: Needs info
      glpi: Aguardando informação
    - taiga: Rejected
      glpi: Rejeitado
    - taiga: Postponed
      glpi: Adiado
    - taiga: Ready
      glpi: Preparado
  entities:
    root-name: Entidade raiz

security:
  webhook:
    allowed-ips:
      - "*"
    glpi-token: ${WEBHOOK_GLPI_TOKEN:}
    taiga-secret: ${WEBHOOK_TAIGA_SECRET:}

ssl:
  skip-verify: ${SSL_SKIP_VERIFY:false}

logging:
  level:
    com:
      chris:
        glpi_taiga_integration: INFO

  # Log em arquivo desativado por padrão em desenvolvimento.
  # Para ativar, defina a variável de ambiente LOG_FILE com o caminho desejado.
  # Exemplo: LOG_FILE=./logs/app.log
  file:
    name: ${LOG_FILE:}

  # Rotação automática
  # só tem efeito quando LOG_FILE está definido
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30 # dias de retenção
      total-size-cap: 200MB

  integration:
    failure-file: integration_failures.log